### ISSUE TITLE
Error while Initializing a python project

### ISSUE THREAD

**Issue by yashppawar** [Shravan-1908/hydra#4] opened 2021-05-12 16:43 UTC
**Describe the bug**
Error while initiating a project

**To Reproduce**
Steps to reproduce the behaviour:
1. create project file `mkdir new-project
2. initialize the project using hydra `hydra init new-project/ python`

**Expected behaviour**
No error should be present, and the fish shell should not give an ❌ emoji at the start of the new line (in the screenshot's last line)

**Screenshots**
![hydra_bug](https://user-images.githubusercontent.com/72196156/118011988-390f2380-b36e-11eb-93e8-2e221fd7d328.png)

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu-based, Pop OS)
 - Version of hydra: (latest) v2.2
- Terminal: Fish

**Comment by Shravan-1908** [comment] 2021-05-12 16:48
Seems like the problem is with the `/` suffix in the project name. Characters like `/` are not allowed in the filenames. The solution will be validating the project name via regular expressions.


Thanks for uncovering this issue. This will be fixed in the next release (v2.2.1).

**Closed** 2021-05-13 08:46 UTC
Labels: bug, next-release
